name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - uses: actions/setup-node@v2
        with:
          node-version: '17.x'
          cache: 'npm'
      - uses: actions/cache@v2
        id: fixtures-cache
        with:
          path: './src/__fixtures__/fetch'
          key: ${{ runner.os }}-fetch-${{ hashFiles('**/__test__/*.ts$') }}
      - name: Install
        run: env NODE_ENV=development npm install --prefer-offline --no-audit && npm install typescript react --save
      - name: Bootstrap fixtures
        run: cd src/__fixtures__/testrepo && npm install --prefer-offline --no-audit
      - name: Test
        run: make test
      - name: Build
        run: env NODE_ENV=production make build
      - id: Publish
        uses: JS-DevTools/npm-publish@v1
        with:
          registry: 'https://registry.npmjs.org/'
          token: ${{ secrets.NPM_TOKEN }}
          access: 'public'
          check-version: true

      - if: steps.publish.outputs.type != 'none'
        run: |
          echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"
